
# board: [ "nice_nano_v2" ] nrfmicro_13 Y52 Y64
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nrfmicro_13
    shield: Y52_left
  - board: nrfmicro_13
    shield: Y52_right
